'use client'
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { signIn } from "next-auth/react";

export default function Home() {
  return (
    <div className='container'>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className='main'>
      <button
        onClick={() => {
          signIn();
        }}
      >
        Login
      </button>
    </main>

    <footer className={'footer'}></footer>
  </div>
  )
}
